# Generated by Django 5.2.4 on 2025-08-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_banners/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='principal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
