# Generated by Django 5.2.4 on 2025-08-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
